FROM ubuntu-jdk

MAINTAINER Ayush "ayushz5716@gmail.com"

ENV version=aws-db-usage
ENV dbuser=postgres
ENV dbpass=password321
ENV jdbcurl=jdbc:postgresql://pmadatabaseaws.ccbfdkqwd5s1.eu-north-1.rds.amazonaws.com:5432/postgres

WORKDIR /usr/local/bin/

ADD pma-app.jar .

ENTRYPOINT ["java","-jar","pma-app.jar"] 